medicalapp/urls.py
from django.conf.urls import url 
from .views import *


urlpatterns = [

    url(r'^hospital-admin/logout/$', AdminLogout.as_view(),
        name='adminlogout'),
    url(r'^hospital-admin/login/$', AdminLogin.as_view(),
        name='adminlogin'),



    url(r'^hospital-admin/$', AdminHomeView.as_view(), name='adminhome'),
    url(r'^hospital-admin/hospital/create/$',
        AdminOrganizationCreateView.as_view(), name='adminorganizationcreate'),
    url(r'^hospital-admin/hospital/(?P<pk>\d+)/update/$',
        AdminOrganizationUpdateView.as_view(), name='adminorganizationupdate'),





    # client
    url(r'^$', ClientHomeView.as_view(), name='clienthome'),
	url(r'^about/$', ClientAboutView.as_view(), name='clientabout'),
	url(r'^gallery/$', ClientGalleryListView.as_view(), name='clientgallerylist'),
	url(r'^blog/$', ClientDepartmentListView.as_view(), name='clientdepartmentlist'),
    url(r'^contact/$', ClientContactView.as_view(), name='clientcontact'),



    ]

medicalproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('medicalapp.urls', namespace='medicalapp'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicalapp/models.py
from django.db import models
from django.utils import timezone


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()




class Organization(TimeStamp):
    name = models.CharField(max_length=255)
    established_date = models.DateTimeField(
        auto_now_add=True, null=True, blank=True)
    phone1 = models.CharField(max_length=20, null=True, blank=True)
    phone2 = models.CharField(max_length=20, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    location = models.CharField(max_length=500)
    image = models.ImageField(upload_to='orgimage/', null=True, blank=True)
    logo = models.ImageField(upload_to="logo/")
    description = models.TextField()
    slogan = models.CharField(max_length=1024, null=True, blank=True)

    def __str__(self):
        return self.name



class Notice(TimeStamp):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.title


class Staff(TimeStamp):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='staff/')
    post = models.CharField(max_length=100)
    phone1 = models.CharField(max_length=20, null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    subject = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name

class Gallery(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title


class Slider(TimeStamp):
    image = models.ImageField(upload_to='slider/')
    caption = models.CharField(max_length=255)

    def __str__(self):
        return self.image.url




class Testimonial(TimeStamp):
    name = models.CharField(max_length=200)
    post = models.CharField(max_length=50)
    says = models.TextField()
    image = models.ImageField(upload_to='testimonial/', null=True, blank=True)


    def __str__(self):
        return self.name


class Message(TimeStamp):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.PositiveIntegerField(null=True, blank=True)
    message = models.TextField()

    def __str__(self):
        return self.name


class Department(TimeStamp):
    image = models.ImageField(upload_to='slider/')
    caption = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return self.image.url

medicalapp/forms.py
from django import forms
from .models import *



class DateTimeInput(forms.DateInput):
    input_type = 'time'


class AdminLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control'}))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}))



class AdminOrganizationCreateForm(forms.ModelForm):
    class Meta:
        model = Organization
        exclude = ['created_at', 'updated_at', 'deleted_at']

    def __init__(self, *args, **kwargs):
        super(AdminOrganizationCreateForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})


class AdminGalleryCreateForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ['title', 'image']

    def __init__(self, *args, **kwargs):
        super(AdminGalleryCreateForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})


class AdminGalleryDeleteForm(forms.ModelForm):

    class Meta:
        model = Gallery
        fields = ['deleted_at']
        widgets = {
            'deleted_at': forms.HiddenInput(),
        }


class AdminNoticeCreateForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = ['title', 'date', 'content']

    def __init__(self, *args, **kwargs):
        super(AdminNoticeCreateForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})


class AdminNoticeDeleteForm(forms.ModelForm):

    class Meta:
        model = Notice
        fields = ['deleted_at']
        widgets = {
            'deleted_at': forms.HiddenInput(),
        }



class AdminStaffCreateForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ['name', 'image', 'post', 'phone1', 'email', 'subject']
        
    def __init__(self, *args, **kwargs):
        super(AdminStaffCreateForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})


class AdminStaffDeleteForm(forms.ModelForm):

    class Meta:
        model = Staff
        fields = ['deleted_at']
        widgets = {
            'deleted_at': forms.HiddenInput(),
        }


class AdminTestimonialCreateForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ['name', 'post', 'says', 'image']

    def __init__(self, *args, **kwargs):
        super(AdminTestimonialCreateForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})


class AdminTestimonialDeleteForm(forms.ModelForm):

    class Meta:
        model = Testimonial
        fields = ['deleted_at']
        widgets = {
            'deleted_at': forms.HiddenInput(),
        }


class AdminSliderCreateForm(forms.ModelForm):
    class Meta:
        model = Slider
        fields = ['image', 'caption']

    def __init__(self, *args, **kwargs):
        super(AdminSliderCreateForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})


class AdminSliderDeleteForm(forms.ModelForm):

    class Meta:
        model = Slider
        fields = ['deleted_at']
        widgets = {
            'deleted_at': forms.HiddenInput(),
        }



class MessageForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Write Your Name.'
            }))
    phone = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Write Your Phone Number.'
            }))
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'Write Your Email.'
            }))
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control', 'placeholder': 'Write Your message.'
            }))
    class Meta:
        model = Message
        fields = ['name', 'phone', 'email', 'message']

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})


class AdminMessageDeleteForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ['deleted_at']
        widgets = {
            'deleted_at': forms.HiddenInput(),
        }


class AdminDepartmentCreateForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['image', 'caption', 'content']

    def __init__(self, *args, **kwargs):
        super(AdminDepartmentCreateForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update(
                {'class': 'form-control'})


class AdminDepartmentDeleteForm(forms.ModelForm):

    class Meta:
        model = Department
        fields = ['deleted_at']
        widgets = {
            'deleted_at': forms.HiddenInput(),
        }

medicalapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import *
from .models import *
from .forms import *


class AdminLogout(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')


class AdminLogin(FormView):
    template_name = "medicalapp/admintemplates/adminlogin.html"
    form_class = AdminLoginForm
    success_url = '/school-admin/'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_superuser:
            login(self.request, user)
        else:
            return render(self.request, self.template_name, {
                'form': form,
                'errors': 'Incorrect username or password'})
        return super().form_valid(form)





class AdminMixin(LoginRequiredMixin, object):
    login_url = '/school-admin/login/'

    def get_context_data(self, *args, **kwargs):
        context = super(AdminMixin, self).get_context_data(*args, **kwargs)
        context['organization'] = Organization.objects.get(id=1)
        return context


class DeleteMixin(LoginRequiredMixin, UpdateView):
    login_url = '/school-admin/login/'

    def form_valid(self, form):
        form.instance.deleted_at = timezone.now()
        form.save()
        return super().form_valid(form)


class AdminHomeView(AdminMixin, TemplateView):
    template_name = 'medicalapp/admintemplates/adminhome.html'

class AdminOrganizationCreateView(AdminMixin, CreateView):
    template_name = 'medicalapp/admintemplates/adminorganizationcreate.html'
    form_class = AdminOrganizationCreateForm
    success_url = reverse_lazy('medicalapp:adminhome')


class AdminOrganizationUpdateView(AdminMixin, UpdateView):
    template_name = 'medicalapp/admintemplates/adminorganizationcreate.html'
    model = Organization
    form_class = AdminOrganizationCreateForm
    success_url = reverse_lazy('medicalapp:adminhome')




# client
class ClientMixin(object):
    def get_context_data(self, *args, **kwargs):
        context = super(ClientMixin, self).get_context_data(*args, **kwargs)
        context['sliders'] = Slider.objects.filter(deleted_at__isnull=True)
        context['notices'] = Notice.objects.filter(deleted_at__isnull=True).order_by('-id')
        context['testimonials'] = Testimonial.objects.filter(
            deleted_at__isnull=True).order_by('-id')
        context['organization'] = Organization.objects.get(id=1)

        return context



class ClientHomeView(ClientMixin, TemplateView):
	template_name='medicalapp/clienttemplates/clienthome.html'


class ClientAboutView(ClientMixin, ListView):
    template_name='medicalapp/clienttemplates/clientabout.html'
    queryset = Staff.objects.filter(deleted_at__isnull=True)
    context_object_name = 'staffs'



class ClientGalleryListView(ClientMixin, ListView):
    template_name='medicalapp/clienttemplates/clientgallerylist.html'
    queryset = Gallery.objects.filter(deleted_at__isnull=True)
    context_object_name ='gallerys'


class ClientContactView(ClientMixin, CreateView):
    template_name='medicalapp/clienttemplates/clientcontact.html'
    form_class = MessageForm
    success_url = '/'


class ClientDepartmentListView(ClientMixin, ListView):
    template_name='medicalapp/clienttemplates/clientdepartmentlist.html'
    queryset = Staff.objects.filter(deleted_at__isnull=True)
    context_object_name = 'staffs'

templates/medicalapp/admintemplates/adminhome.html
{% extends 'medicalapp/admintemplates/base.html' %}
{% load static %}
{% block home %}active{% endblock home %}


{% block content %}
<div class="container-fluid bg-light">
	{% if organization %}
    <div class="content">
        <h2 style="color: green;"><img src="{{organization.logo.url}}" width="100" style="border: 4px solid red;">{{organization.name|striptags}}, &nbsp;<small>"{{organization.slogan}}"</small></h2>
        <a href="{% url 'medicalapp:adminorganizationupdate' organization.id %}" class="btn btn-primary pull-right">Update Organization</a>
        <hr>

        <h5>{{organization.location}}</h5>
        <h5>{{organization.established_date}}</h5>
        <h5>{{organization.phone1}}</h5>
        <h5>{{organization.phone2}}</h5>
        <h5>{{organization.email}}</h5>
    </div>
    <div class="row clearfix">
    	<img src="{{organization.image.url}}" class="img-responsive">
    	 <p>{{organization.description|safe}}</p>
    </div>
    <a href="{% url 'medicalapp:adminorganizationupdate' organization.id %}" class="btn btn-primary pull-right">Update Organization</a><hr><br><br>
    {% else %}
    <div class="row clearfix">
    	<a href="{% url 'medicalapp:adminorganizationcreate' %}">Create Organization</a>
    </div>


    {% endif %}
</div>
{% endblock content %}

templates/medicalapp/admintemplates/adminlogin.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<head>
    <title>{% block title %}Login{% endblock title %}</title>
    <link rel="icon" href="{% static 'adminstatic/images/favicon.ico' %}" type="image/x-icon">
    <link href="{% static 'adminstatic/plugins/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
</head>
</head>
<body class="container">
<div class="row">
	<div class="col-md-4 col-md-offset-4 bg-primary">
		<h3 class="text-center">Administration Login</h3><hr>
		
		{% if errors %}
		<h3 style="color: red;">{{errors}}</h3>
		{% else %}
		<h3>Enter your secret username and password</h3>
		{% endif %}
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<br>
			<button class="btn btn-block btn-default">Submit</button>
		</form><br>
	</div>
</div>	
</body>
</html>

templates/medicalapp/admintemplates/adminorganizationcreate.html
{% extends 'medicalapp/admintemplates/base.html' %}
{% load static %}
{% block home %}active{% endblock home %}


{% block content %}
<div class="container-fluid">
    <div class="block-header">
        <h2>Create or Update Organization</h2>
    </div>

    <div class="row clearfix">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form.as_p}}
            <button class="btn btn-primary">Submit</button>
        </form>
        <hr>
    </div>
</div>
{% endblock content %}

templates/medicalapp/admintemplates/admintestimonialcreate.html
{% extends 'medicalapp/admintemplates/base.html' %}
{% load static %}
{% block testimonials %}active{% endblock testimonials %}


{% block content %}
<div class="container-fluid">
    <div class="block-header">
        <h2>Create Staff</h2>
    </div>

    <div class="row clearfix">
        <form method="POST" enctype="multipart/form-data">
        	{% csrf_token %}
        	{{form.media}}
        	{{form.as_p}}
        	<button class="btn btn-primary">Submit</button>
        </form>
        <hr>
    </div>
</div>
{% endblock content %}

templates/medicalapp/admintemplates/admintestimonialdelete.html
 <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h3 class="modal-title">Delete {{object.name}}</h3>
</div>
<form class="form" method="POST"  action="{% url 'medicalapp:admintestimonialdelete' object.id %}">{% csrf_token %}
    <div class="modal-body">
        Are you sure you want to delete <h5>{{object.name}}</h5>?
    </div>
    <div class="modal-footer">
        <button class="btn btn-danger">Delete</button>
        <button class="btn btn-default" data-dismiss="modal">Cancel</button>
    </div>
</form>

templates/medicalapp/admintemplates/admintestimoniallist.html
{% extends 'medicalapp/admintemplates/base.html' %}
{% load static %}
{% block testimonials %}active{% endblock testimonials%}
{% block css %}
<link href="{% static 'adminstatic/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
        <div class="container-fluid">
            <!-- Basic Examples -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Testimonial list
                            </h2>
                            <h2 class="pull-right">
                               <a href="{% url 'medicalapp:admintestimonialcreate' %}">Add New</i></a>
                            </h2>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th>SN</th>
                                            <th>Name</th>
                                            <th>syas</th>
                                            <th>image</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>SN</th>
                                            <th>Name</th>
                                            <th>says</th>
                                            <th>image</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                    	{% for testimonial in alltestimonials %}
                                        <tr>
                                            <td>{{forloop.counter}}</td>
                                            <td>{{testimonial.name}}</td>
                                            <td>{{testimonial.post}}</td>
                                            <td>{{testimonial.says}}</td>
                                            <td><img src="{{testimonial.image.url}}" width="50"></td>

                                            <td>
                                            	<a href="{% url 'medicalapp:admintestimonialupdate' testimonial.id %}" class="btn btn-default"> Update</a>
                                            	<a href="{% url 'medicalapp:admintestimonialdelete' testimonial.id %}" class="btn btn-danger" data-toggle="modal" data-target="#schoolmodal"> Delete</a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'adminstatic/plugins/jquery-datatable/jquery.dataTables.js' %}"></script>
<script src="{% static 'adminstatic/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'adminstatic/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'adminstatic/js/pages/tables/jquery-datatable.js' %}"></script>
{% endblock javascript %}